Repository micronaut-projects/micronaut-azure, pull requests merged in 2020-10, with the labels that each got.

#87 fix: start application context if app context is null
  azure-function-http-test/src/main/java/io/micronaut/azure/function/http/test/AzureFunctionEmbeddedServer.java
  azure-function/src/main/java/io/micronaut/azure/function/AzureFunction.java
Labels: type: improvement

#95 [azure] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#96 [azure] Update common files for branch 2.0.x
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#97 Dependency upgrades
  azure-function-http-test/build.gradle
Labels: type: dependency-upgrade
