Repository micronaut-projects/micronaut-azure, pull requests merged in 2020-09, with the labels that each got.

#51 Dependency upgrades
  azure-function-http/build.gradle
  azure-function/build.gradle
  doc-examples/example-groovy/build.gradle
  doc-examples/example-java/build.gradle
  doc-examples/example-kotlin/build.gradle
  examples/azure-functions-example/build.gradle
Labels: type: dependency-upgrade

#50 [azure] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#59 doc: release history points to github relases
  src/main/docs/guide/releaseHistory.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#60 ci: set github core branch to 2.0.x
  gradle.properties
Labels: relates-to: build

#62 Dependency upgrades
  doc-examples/example-kotlin/build.gradle
Labels: type: dependency-upgrade

#61 build: remove docs-examples if
  build.gradle
Labels: relates-to: build

#65 Dependency upgrades
  build.gradle
Labels: type: dependency-upgrade

#67 fix: AzureFunction implements AutoCloseable
  azure-function/src/main/java/io/micronaut/azure/function/AzureFunction.java
  azure-function/src/test/groovy/io/micronaut/azure/function/AzureFunctionSpec.groovy
Labels: type: improvement

#68 fix: AzureFunction implements AutoCloseable
  azure-function/src/main/java/io/micronaut/azure/function/AzureFunction.java
  azure-function/src/test/groovy/io/micronaut/azure/function/AzureFunctionSpec.groovy
Labels: type: improvement

#70 Remove wildcard imports
  doc-examples/example-groovy/src/test/groovy/example/BlobFunction.groovy
  doc-examples/example-groovy/src/test/groovy/example/MyHttpFunction.groovy
  doc-examples/example-java/src/test/java/example/BlobFunction.java
  doc-examples/example-java/src/test/java/example/MyHttpFunction.java
  doc-examples/example-kotlin/src/test/kotlin/example/BlobFunction.kt
  doc-examples/example-kotlin/src/test/kotlin/example/MyHttpFunction.kt
Labels: type: improvement

#69 checkstyle: constructor wrong order
  azure-function/src/main/java/io/micronaut/azure/function/AzureFunction.java
Labels: type: improvement

#71 Merge 1.0.x into master
  azure-function/src/main/java/io/micronaut/azure/function/AzureFunction.java
  doc-examples/example-groovy/src/test/groovy/example/BlobFunction.groovy
  doc-examples/example-groovy/src/test/groovy/example/MyHttpFunction.groovy
  doc-examples/example-java/src/test/java/example/BlobFunction.java
  doc-examples/example-java/src/test/java/example/MyHttpFunction.java
  doc-examples/example-kotlin/src/test/kotlin/example/BlobFunction.kt
  doc-examples/example-kotlin/src/test/kotlin/example/MyHttpFunction.kt
Labels: type: improvement

#72 [azure] Update common files for branch 1.0.x
  .github/workflows/gradle.yml
Labels: relates-to: build

#75 [azure] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build

#80 ci: bump up micronaut docs to 1.0.24
  gradle.properties
Labels: relates-to: build

#79 ci: remove unused micronautBuild property
  gradle.properties
Labels: relates-to: build
