Repository micronaut-projects/micronaut-azure, pull requests merged in 2021-05, with the labels that each got.

#203 ci: graalvm 21.0.0.2 to 21.1.0 gradle 7.0.0 to 7.0.2
  .github/workflows/graalvm.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#205 fix: normalize http headers
  azure-function-http/src/main/java/io/micronaut/azure/function/http/AzureFunctionHttpRequest.java
  azure-function-http/src/main/java/io/micronaut/azure/function/http/AzureMultiValueMap.java
  azure-function-http/src/test/groovy/io/micronaut/azure/function/http/HttpHeaderCaseInsensitiveSpec.groovy
  azure-function-http/src/test/java/io/micronaut/azure/function/http/HeadersController.java
Labels: type: bug

#206 test: close function
  azure-function-http/src/test/groovy/io/micronaut/azure/function/http/ParameterBindingSpec.groovy
Labels: type: improvement
