Repository micronaut-projects/micronaut-azure, pull requests merged in 2022-06, with the labels that each got.

#345 [azure] Update common files for branch master
  .github/release.yml
  .github/renovate.json
  .github/workflows/dependency-update.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#346 Add Gradle Catalog to manage dependencies
  azure-bom/build.gradle
  azure-function-http-test/build.gradle
  azure-function-http/build.gradle
  azure-function/build.gradle
  azure-sdk/build.gradle
  config/checkstyle/.rsync-filter
  doc-examples/example-groovy/build.gradle
  doc-examples/example-java/build.gradle
  doc-examples/example-kotlin/build.gradle
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle
Labels: type: improvement

#347 Add support for Azure KeyVault
  azure-sdk/src/main/java/io/micronaut/azure/credentials/AzureCredentialFactory.java
  azure-sdk/src/main/java/io/micronaut/azure/credentials/AzureCredentialsConfiguration.java
  azure-secret-manager/build.gradle
  azure-secret-manager/src/main/java/io/micronaut/azure/secretmanager/AzureVaultConfigurationClient.java
  azure-secret-manager/src/main/java/io/micronaut/azure/secretmanager/SecretManagerFactory.java
  azure-secret-manager/src/main/java/io/micronaut/azure/secretmanager/client/DefaultSecretKeyVaultClient.java
  azure-secret-manager/src/main/java/io/micronaut/azure/secretmanager/client/SecretKeyVaultClient.java
  azure-secret-manager/src/main/java/io/micronaut/azure/secretmanager/configuration/AzureKeyVaultConfigurationProperties.java
  azure-secret-manager/src/test/groovy/io/micronaut/azure/secretmanager/AzureSecretKeyVaultClientSpec.groovy
  azure-secret-manager/src/test/groovy/io/micronaut/azure/secretmanager/AzureSecretVaultConfigurationClientSpec.groovy
  azure-secret-manager/src/test/groovy/io/micronaut/azure/secretmanager/AzureSecretVaultConfigurationSpec.groovy
  azure-secret-manager/src/test/resources/logback.xml
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle
  src/main/docs/guide/azureKeyVault.adoc
  src/main/docs/guide/azureKeyVault/distributedConfiguration.adoc
  src/main/docs/guide/toc.yml
  src/main/docs/resources/img/key_vault_url.png
Labels: type: enhancement

#349 [azure] Update common files for branch master
  .editorconfig
  .gitattributes
  gradlew.bat
Labels: relates-to: build
