Repository micronaut-projects/micronaut-azure, pull requests merged in 2023-06, with the labels that each got.

#484 ci: GitHub renovate schedule
  .github/renovate.json
Labels: relates-to: build

#491 [azure] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
Labels: relates-to: build

#500 ci: checkout workflow 3.5.3
  .github/workflows/release.yml
Labels: relates-to: build

#498 Typo in 'Azure Blob Storage' vs 'Blog'
  src/main/docs/guide/toc.yml
Labels: type: docs

#509 Azure HTTP Functions compliant with TCK
  azure-function-http-test/src/main/java/io/micronaut/azure/function/http/test/AzureFunctionEmbeddedServer.java
  azure-function-http-test/src/test/groovy/io/micronaut/azure/function/http/test/AzureFunctionCorsSpec.groovy
  azure-function-http-test/src/test/groovy/io/micronaut/azure/function/http/test/AzureFunctionEmbeddedServerSpec.groovy
  azure-function-http-test/src/test/groovy/io/micronaut/azure/function/http/test/ContextAzureFunctionEmbeddedServerSpec.groovy
  azure-function-http/build.gradle.kts
  azure-function-http/src/main/java/io/micronaut/azure/function/http/AzureAnnotatedMethodRouteBuilder.java
  azure-function-http/src/main/java/io/micronaut/azure/function/http/AzureBinderRegistry.java
  azure-function-http/src/main/java/io/micronaut/azure/function/http/AzureCookies.java
  azure-function-http/src/main/java/io/micronaut/azure/function/http/AzureFunctionHttpRequest.java
  azure-function-http/src/main/java/io/micronaut/azure/function/http/AzureFunctionHttpResponse.java
  azure-function-http/src/main/java/io/micronaut/azure/function/http/AzureHttpFunction.java
  azure-function-http/src/main/java/io/micronaut/azure/function/http/AzureHttpResponseMessage.java
  azure-function-http/src/main/java/io/micronaut/azure/function/http/AzureHttpResponseMessageAdapter.java
  azure-function-http/src/main/java/io/micronaut/azure/function/http/AzureMultiValueMap.java
  azure-function-http/src/main/java/io/micronaut/azure/function/http/AzureMutableHeaders.java
  azure-function-http/src/main/java/io/micronaut/azure/function/http/AzureServletBodyBinder.java
  azure-function-http/src/main/java/io/micronaut/azure/function/http/BinaryContentConfiguration.java
  azure-function-http/src/main/java/io/micronaut/azure/function/http/DefaultHttpRequestMessageBuilder.java
  azure-function-http/src/main/java/io/micronaut/azure/function/http/HttpHandler.java
  azure-function-http/src/main/java/io/micronaut/azure/function/http/HttpRequestMessageBuilder.java
  azure-function-http/src/main/java/io/micronaut/azure/function/http/HttpRequestMessageHandler.java
  azure-function-http/src/main/java/io/micronaut/azure/function/http/QueryStringDecoder.java
  azure-function-http/src/main/java/io/micronaut/azure/function/http/ResponseBuilder.java
  azure-function-http/src/test/groovy/io/micronaut/azure/function/http/FormSpec.groovy
  azure-function-http/src/test/groovy/io/micronaut/azure/function/http/HttpHeaderCaseInsensitiveSpec.groovy
  azure-function-http/src/test/groovy/io/micronaut/azure/function/http/ParameterBindingSpec.groovy
  azure-function-http/src/test/groovy/io/micronaut/azure/function/http/TestUtils.java
  azure-function-http/src/test/java/io/micronaut/azure/function/http/HeadersController.java
  buildSrc/src/main/groovy/io.micronaut.build.internal.azure-base.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.http-server-tck-module.gradle
  config/accepted-api-changes.json
  gradle/libs.versions.toml
  settings.gradle
  src/main/docs/guide/azureFunction/azureHttpFunctions.adoc
  src/main/docs/guide/azureFunction/azureHttpFunctions/routePrefix.adoc
  src/main/docs/guide/azureFunction/simpleAzureFunctions.adoc
  src/main/docs/guide/azureSdk.adoc
  src/main/docs/guide/breaks.adoc
  src/main/docs/guide/toc.yml
  src/main/docs/guide/whatsNew.adoc
  test-suite-azure-function-http-context-path/build.gradle.kts
  test-suite-azure-function-http-context-path/src/test/groovy/io/micronaut/azure/DemoFunctionSpec.groovy
  test-suite-azure-function-http-context-path/src/test/java/io/micronaut/azure/DemoController.java
  test-suite-azure-function-http-context-path/src/test/java/io/micronaut/azure/Function.java
  test-suite-azure-function-http-context-path/src/test/resources/application.yml
  test-suite-azure-function-http-context-path/src/test/resources/logback.xml
  test-suite-http-server-tck-azure-function-http-test/build.gradle.kts
  test-suite-http-server-tck-azure-function-http-test/src/test/java/io/micronaut/http/server/tck/azurehttpfunction/tests/AzureFunctionHttpTestHttpServerTestSuite.java
  test-suite-http-server-tck-azure-function-http-test/src/test/resources/META-INF/services/io.micronaut.http.tck.ServerUnderTestProvider
  test-suite-http-server-tck-azure-function-http-test/src/test/resources/application.yml
  test-suite-http-server-tck-azure-function-http-test/src/test/resources/logback.xml
  test-suite-http-server-tck-azure-function-http/src/test/java/io/micronaut/http/server/tck/azurehttpfunction/AzureFunctionHttpServerUnderTest.java
  test-suite-http-server-tck-azure-function-http/src/test/java/io/micronaut/http/server/tck/azurehttpfunction/AzureRequestEventFactory.java
  test-suite-http-server-tck-azure-function-http/src/test/java/io/micronaut/http/server/tck/azurehttpfunction/DefaultExecutionContext.java
  test-suite-http-server-tck-azure-function-http/src/test/java/io/micronaut/http/server/tck/azurehttpfunction/HttpRequestMessageAdapter.java
  test-suite-http-server-tck-azure-function-http/src/test/java/io/micronaut/http/server/tck/azurehttpfunction/HttpResponseMessageAdapter.java
  test-suite-http-server-tck-azure-function-http/src/test/java/io/micronaut/http/server/tck/azurehttpfunction/tests/AzureFunctionHttpHttpServerTestSuite.java
Labels: type: enhancement
