Repository micronaut-projects/micronaut-azure, pull requests merged in 2024-08, with the labels that each got.

#715 [azure] Update common files for branch 5.5.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build

#726 [azure] Update common files for branch 5.6.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#728 Split docs in sections
  src/main/docs/guide/azureLogging.adoc
  src/main/docs/guide/azureLogging/azureLoggingApplicationConfiguration.adoc
  src/main/docs/guide/azureLogging/browsingTheLogs.adoc
  src/main/docs/guide/azureLogging/createAzureLoggingResources.adoc
  src/main/docs/guide/azureLogging/emergencyAppender.adoc
  src/main/docs/guide/azureLogging/logbackConfiguration.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#725 Add support for Azure Logging
  azure-logging/build.gradle
  azure-logging/src/main/java/io/micronaut/azure/logging/AzureAppender.java
  azure-logging/src/main/java/io/micronaut/azure/logging/AzureJsonFormatter.java
  azure-logging/src/main/java/io/micronaut/azure/logging/AzureLoggingClient.java
  azure-logging/src/main/java/io/micronaut/azure/logging/AzureLoggingConfigurationProperties.java
  azure-logging/src/main/java/io/micronaut/azure/logging/ClientFactory.java
  azure-logging/src/main/java/io/micronaut/azure/logging/ClientWrapper.java
  azure-logging/src/main/java/io/micronaut/azure/logging/DefaultClientWrapper.java
  azure-logging/src/main/java/io/micronaut/azure/logging/LogEntry.java
  azure-logging/src/main/java/io/micronaut/azure/logging/package-info.java
  azure-logging/src/test/groovy/io/micronaut/azure/logging/AzureAppenderSpec.groovy
  azure-logging/src/test/groovy/io/micronaut/azure/logging/AzureLoggingClientSpec.groovy
  azure-logging/src/test/groovy/io/micronaut/azure/logging/AzureLoggingConfigurationSpec.groovy
  azure-logging/src/test/groovy/io/micronaut/azure/logging/AzureLoggingSpec.groovy
  azure-logging/src/test/groovy/io/micronaut/azure/logging/LogEntrySpec.groovy
  azure-logging/src/test/resources/application-test.properties
  azure-logging/src/test/resources/logback.xml
  gradle/libs.versions.toml
  settings.gradle
  src/main/docs/guide/azureLogging.adoc
  src/main/docs/guide/azureLogging/azureLoggingApplicationConfiguration.adoc
  src/main/docs/guide/azureLogging/browsingTheLogs.adoc
  src/main/docs/guide/azureLogging/createAzureLoggingResources.adoc
  src/main/docs/guide/azureLogging/emergencyAppender.adoc
  src/main/docs/guide/azureLogging/logbackConfiguration.adoc
  src/main/docs/guide/toc.yml
Labels: type: enhancement
