Repository micronaut-projects/micronaut-azure, pull requests merged in 2024-03, with the labels that each got.

#644 docs: note that Azure Key Vault Config needs micronaut-discovery-client dependency.
  src/main/docs/guide/azureKeyVault.adoc
Labels: type: docs

#650 Fix concurrent calls for Azure Functions
  azure-function-http/src/main/java/io/micronaut/azure/function/http/AzureHttpFunction.java
  azure-function/src/main/java/io/micronaut/azure/function/AzureFunction.java
  build.gradle
  config/accepted-api-changes.json
  doc-examples/example-groovy/build.gradle.kts
  doc-examples/example-java/build.gradle.kts
  doc-examples/example-kotlin/build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle
  test-suite-dockerised/build.gradle.kts
  test-suite-dockerised/host.json
  test-suite-dockerised/local.settings.json
  test-suite-dockerised/src/main/java/example/micronaut/DefaultController.java
  test-suite-dockerised/src/main/java/example/micronaut/Function.java
  test-suite-dockerised/src/main/resources/logback.xml
  test-suite-dockerised/src/test/groovy/example/micronaut/ConcurrentFunctionSpec.groovy
Labels: type: bug, type: breaking

#657 [azure] Update common files for branch master
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build
